block_placeholder.placeholder_reference.*:
  type: config_entity
  label: Block placeholder reference
  mapping:
    id:
      type: string
      label: Placeholder identifier
    label:
      type: string
      label: Placeholder label
    reference_limit_type:
      type: string
      label: Reference limit type
    reference_limited_value:
      type: integer
      label: Reference limited value
    block_types:
      type: sequence
      label: Allowed block types
      sequence:
        type: string
        label: Entity block type
